---
title: "Additional Plots"
author: "Sarah Pickresgill"
date: "6/24/2021"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(ggforce)
library(dplyr)
library(readxl)
library(tinytex)

load("Outputs/goal.q30.Rda")

#colors from https://spectrum.adobe.com/page/color-for-data-visualization/
ryb<-c("#d73027","#fdae61", "#ffffbf","#abd9ea", "#4575b4")
ryb2<-c("#c65154","#f0a882", "#ffffe0","#89c0c4", "#208288")
ryb2_reverse<-c("#208288", "#89c0c4", "#ffffe0", "#f0a882", "#c65154")
pwb<-c("#cc415a","#ed9ab0", "#faf0ff","#92b2de", "#2f74b3")
ybp<-c("#3c1f5c","#33628e", "#2d7b8d","#20a386", "#fde725")

```

Global Heat Map of covid and intervention scale-up scenarios

```{r fig.width=8, warning=FALSE}

ggplot(summary, aes(y=s_covid, x=s_inc*100, fill=adj.diff/1000000))+
  geom_tile()+
  geom_text(aes(label=paste0(signif(100*n.reaches/124, digits=2), "%")), color="black")+
  scale_fill_gradientn(colors=ryb2_reverse, values=c(0,0.5,1))+
  labs(fill="NCD deaths (millions) in excess \nof the most optimistic scenario")+
  ylab("Covid scaling factor for underreporting")+
  xlab("Maximum annual increase (%) in intervention coverage")+
  ggtitle("Global excess NCD deaths and the number of countries \nachieving a one-third reduction in 40q30 \nby each covid and intervention scale-up scenario")+
labs(caption = "\n*Text numbers represent the percent of LMICs achieving a 1/3 reduction in 40q30 by 2030")

##Other way
ggplot(summary, aes(y=s_covid, x=s_inc*100, fill=n.reaches))+ 
  geom_tile()+ 
  geom_text(aes(label=signif(adj.diff/1000000,digits=3)), color="black")+ 
  scale_fill_gradientn(colors=ryb2, values=c(0,0.5,1))+ 
  labs(fill="Number of countries achieving\n40q30 SDG target")+ 
  ylab("Covid scaling factor for underreporting")+ 
  xlab("Maximum annual increase (%) in intervention coverage")+ 
  ggtitle("Global excess NCD deaths and the number of countries \nachieving a one-third reduction in 40q30 \nby each covid and intervention scale-up scenario")+ 
  labs(caption = "\n*Text numbers represent NCD deaths (millions) in excess of the most optimistic scenario")


```

Quick look at country-specific patterns

```{r fig.width=8, warning=FALSE}

deaths<-ncd.deaths.out%>%group_by(location, s_covid, s_inc)%>%summarise(ncd.deaths=sum(adj.ncd)/1000000)
progress<-goal.q30.out%>%mutate(prog=100*(Baseline_2015-Adjusted_2030)/(Baseline_2015-Target_40q30))%>%
  rename(location = location_name)%>%select(location, s_covid, s_inc, prog)
progress$prog[progress$prog>100]<-100

plot2<-full_join(deaths, progress)

ggplot(plot2%>%filter(location=="Brazil"), aes(y=s_covid, x=s_inc, fill=prog))+
  geom_tile()+
  geom_text(aes(label=signif(ncd.deaths, digits=3)))+
  scale_fill_gradientn(colors=ryb2, values=c(0,0.5,1))+
  labs(fill="Progress towards 1/3 reduction in 40q30 (%)")+
  xlab("Maximum annual increase (%) in intervention coverage")+
  ylab("Covid scaling factor for underreporting")+
  ggtitle("Total NCD deaths (millions) and progress towards 40q30 goal (%) \nby each covid and intervention scale-up scenario\n\nBrazil, 2015-2030")+
labs(caption = "\n*Text numbers represent the total number of NCD deaths (in millions)")

ggplot(plot2%>%filter(location=="Brazil"), aes(y=s_covid, x=s_inc, fill=ncd.deaths))+
  geom_tile()+
  geom_text(aes(label=paste0(signif(prog, digits=2),"%")))+
  scale_fill_gradientn(colors=ryb2_reverse, values=c(0,0.5,1))+
  labs(fill="Total NCD deaths (millions)")+
  xlab("Maximum annual increase (%) in intervention coverage")+
  ylab("Covid scaling factor for underreporting")+
  ggtitle("Total NCD deaths (millions) and progress towards 40q30 goal (%) \nby each covid and intervention scale-up scenario\n\nBrazil, 2015-2030")+
labs(caption = "\n*Text numbers represent the percent progress towards the 40q30 SDG target")

ggplot(plot2%>%filter(location=="China"), aes(y=s_covid, x=s_inc, fill=ncd.deaths))+
  geom_tile()+
  geom_text(aes(label=paste0(signif(prog, digits=2),"%")))+
  scale_fill_gradientn(colors=ryb2_reverse, values=c(0,0.5,1))+
  labs(fill="Total NCD deaths (millions)")+
  xlab("Maximum annual increase (%) in intervention coverage")+
  ylab("Covid scaling factor for underreporting")+
  ggtitle("Total NCD deaths (millions) and progress towards 40q30 goal (%) \nby each covid and intervention scale-up scenario\n\nChina, 2015-2030")+
labs(caption = "\n*Text numbers represent the percent progress towards the 40q30 SDG target")


```


Looking at the covid shock to 40q30 over time

```{r fig.width=8, warning=FALSE}

base<-all.q30.out%>%filter(s_covid==0 & s_inc==0)%>%mutate(scenario="Baseline")%>%
  select(Adjusted, year_id, location_name, scenario)
best<-all.q30.out%>%filter(s_covid==0 & s_inc==0.05 & year_id>=2019)%>%mutate(scenario="Most optimistic")%>%
  select(Adjusted, year_id, location_name, scenario)
middle<-all.q30.out%>%filter(s_covid==1 & s_inc==0.03 & year_id>=2019)%>%mutate(scenario="Moderate")%>%
  select(Adjusted, year_id, location_name, scenario)
worst<-all.q30.out%>%filter(s_covid==2 & s_inc==0 & year_id>=2019)%>%mutate(scenario="Most pessimistic")%>%
  select(Adjusted, year_id, location_name, scenario)

plot3<-bind_rows(base, best, middle, worst)
plot3$scenario<-factor(plot3$scenario, levels=c("Baseline", "Most pessimistic", "Moderate", "Most optimistic"))

#add splines
#p1<-plot3%>%filter(scenario=="Most pessimistic", location_name=="Brazil")
#spline1 <- as.data.frame(spline(p1$year_id, p1$Adjusted))
#spline1$scenario<-"Most pessimistic"
brazil_target<-base$Adjusted[base$year_id==2015 & base$location_name=="Brazil"]*(2/3)

ggplot(plot3%>%filter(location_name=="Brazil"), aes(x=year_id, y=Adjusted, color=scenario))+
  geom_point()+
  geom_line()+
  #stat_smooth(aes(x=year_id, y=Adjusted), formula =y~poly(x,6), method="lm", se=F)
  #stat_smooth(aes(x=year_id, y=Adjusted), formula=y~s(x,k=10), method="gam", se=F)+
  geom_line(y=brazil_target, color="darkgrey", lty=2)+
  ylab("40q30 (%)")+
  xlab("Year")+
  ggtitle("Projected 40q30 over time, Brazil")+
  labs(color="Scenario")+
  coord_cartesian(ylim=c(0,40))+
  scale_color_manual(values=c("black", "#cc415a",   "#057fee", "#22a884"))+
  annotate(geom="text", x=2027, y=brazil_target-2, label="Target: 1/3 reduction in 40q30", color="darkgrey")
  

## Crude average for global plot

global<-plot3%>%group_by(scenario,year_id)%>%summarise(q30=mean(Adjusted))
global_target<-global$q30[global$year_id==2015 & global$scenario=="Baseline"]*(2/3)

ggplot(global, aes(x=year_id, y=q30, color=scenario))+
  geom_point()+
  geom_line()+
  geom_line(y=global_target, color="darkgrey", lty=2)+
  ylab("40q30 (%)")+
  xlab("Year")+
  ggtitle("Projected 40q30 over time, Global")+
  labs(color="Scenario")+
  coord_cartesian(ylim=c(0,40))+
  scale_color_manual(values=c("black", "#cc415a",   "#057fee", "#22a884"))+
  annotate(geom="text", x=2027, y=global_target-2, label="Target: 1/3 reduction in 40q30", color="darkgrey")

```

Cost  per change in 40q30 vs. cost per DALY averted

```{r fig.width=8, warning=FALSE}
cost<-read.csv("Outputs/All_ICER_2030.csv", stringsAsFactors = F)%>%select(c(increment, Code, Country, NCD_region, Revised.Intervention.Name))%>%rename(Description = Revised.Intervention.Name)
load("Outputs/icer_rank_output.Rda")

codes<-unique(read_excel("Input_Data/EfficacyData6.xlsx")%>%select(c(Description, NCD)))
codes$NCDcode<-paste0("C", codes$NCD)
codes$NCDcode[codes$Description=="Management of depression disorders with psycological and generic antidepressant therapy"]<-"C2.10"

tot_dalys<-all.dalys%>%rename(Country = location_name)%>%group_by(Country, Code)%>%
  summarise(DALY=sum(DALY.ave))%>%rename(NCDcode = Code)
#just the end change in 2030?
tot_40q30<-all.q30%>%filter(year_id==2030)%>%rename(Country = location_name)%>%
  select(c(Country, Code, q30.ave))%>%rename(NCDcode = Code)

benefits<-full_join(tot_dalys, tot_40q30, by=c("Country", "NCDcode"))
benefits<-left_join(benefits, codes, by="NCDcode")

plot<-na.omit(left_join(cost, benefits, by=c("Description", "Country")))%>%mutate(ICER1 = increment/DALY, ICER2=increment/q30.ave)
plot$platform<-str_extract(plot$Code, "[A-Z]+")

global<-plot%>%group_by(Description, platform)%>%summarise(ICER1=mean(ICER1), ICER2=mean(ICER2))

global$platform<-factor(global$platform, levels=c("HC", "FLH", "RH"), labels=c("Health Centre", "First-level hospital", "Refereal hospital"))

ggplot(global, aes(x=log(ICER1), y=log(ICER2), color=platform))+
  geom_point()+
  ggtitle("Incremental cost per DALY averted vs. incremental \ncost per change in 40q30 by intervention")+
  labs(color="Platform")+
  xlab("Log(cost per DALY averted)")+
  ylab("Log(cost per % change in 40q30)")


#add text?
ggplot(global, aes(x=log(ICER1), y=log(ICER2), color=platform))+
  geom_point()+
  ggtitle("Incremental cost per DALY averted vs. incremental \ncost per change in 40q30 by intervention")+
  labs(color="Platform")+
  xlab("Log(cost per DALY averted)")+
  ylab("Log(cost per % change in 40q30)")+
  geom_text(size=3, aes(label=paste0(substr(Description, 0,50),"...")), hjust=-0.01, vjust=0)+
  coord_cartesian(xlim=c(-5,20))

#still need to figure out how to dodge text better..

```
