---
title: "Additional Plots"
author: "Sarah Pickresgill"
date: "6/24/2021"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(ggforce)
library(dplyr)
library(readxl)
library(tinytex)

load("Outputs/goal.q30.Rda")
```

Global Heat Maps

```{r fig.width=8, include=FALSE}
##need to add text label for numbers

ggplot(summary, aes(x=s_covid, y=s_inc*100, fill=adj.diff))+
  geom_tile()+
  geom_text(aes(label=n.reaches), color="black")+
  scale_fill_gradientn(colors=c("#3c1f5c","#33628e", "#2d7b8d","#20a386", "#fde725"), values=c(0,0.1,1))+
  labs(fill="Excess NCD deaths")+
  ylab("Annual absolute increase in coverage (%)")+
  xlab("Covid adjustment factor")+
  ggtitle("Global excess NCD deaths and the number of countries \nachieving a one-third reduction in 40q30 \nby each covid and intervention scale-up scenario")+
labs(caption = "*Text numbers represent number of countries achieving 40q30 target")

ggplot(summary, aes(x=s_covid, y=s_inc*100, fill=n.reaches))+
  geom_tile()+
  geom_text(aes(label=signif(adj.diff/1000000, digits=2)), color="black")+
  scale_fill_gradientn(colors=c("#3c1f5c","#33628e", "#2d7b8d","#20a386", "#fde725"), values=c(0,0.1,1))+
  labs(fill="Number of countries to reach 40q30 target")+
  ylab("Annual absolute increase in coverage (%)")+
  xlab("Covid adjustment factor")+
  ggtitle("Global excess NCD deaths (millions) and the \nnumber of countries achieving a one-third reduction in 40q30 \nby each covid and intervention scale-up scenario")+
labs(caption = "*Text numbers represent the number of excess NCD deaths (in millions")

```

Quick look at country-specific patterns

```{r fig.width=8}

deaths<-ncd.deaths.out%>%group_by(location, s_covid, s_inc)%>%summarise(ncd.deaths=sum(adj.ncd)/1000000)
progress<-goal.q30.out%>%mutate(prog=100*(Baseline_2015-Adjusted_2030)/(Baseline_2015-Target_40q30))%>%
  rename(location = location_name)%>%select(location, s_covid, s_inc, prog)
progress$prog[progress$prog>100]<-100

plot2<-full_join(deaths, progress)

ggplot(plot2%>%filter(location=="Brazil"), aes(x=s_covid, y=s_inc, fill=prog))+
  geom_tile()+
  geom_text(aes(label=signif(ncd.deaths, digits=3)))+
  scale_fill_gradientn(colors=c("#3c1f5c","#33628e", "#2d7b8d","#20a386", "#fde725"), values=c(0,0.5,1))+
  labs(fill="Progress towards 1/3 reduction in 40q30 (%)")+
  ylab("Annual absolute increase in coverage (%)")+
  xlab("Covid adjustment factor")+
  ggtitle("Total NCD deaths (millions) and progress towards 40q30 goal (%) \nby each covid and intervention scale-up scenario\n\nBrazil, 2015-2030")+
labs(caption = "*Text numbers represent the total number of NCD deaths (in millions)")

ggplot(plot2%>%filter(location=="Brazil"), aes(x=s_covid, y=s_inc, fill=ncd.deaths))+
  geom_tile()+
  geom_text(aes(label=paste0(signif(prog, digits=2),"%")))+
  scale_fill_gradientn(colors=c("#3c1f5c","#33628e", "#2d7b8d","#20a386", "#fde725"), values=c(0,0.5,1))+
  labs(fill="Total number of NCD deaths (millions)")+
  ylab("Annual absolute increase in coverage (%)")+
  xlab("Covid adjustment factor")+
  ggtitle("Total NCD deaths (millions) and progress towards 40q30 goal (%) \nby each covid and intervention scale-up scenario \n\nBrazil, 2015-2030")+
labs(caption = "*Text numbers represent the % progress towards achieving 40q30 target")


ggplot(plot2%>%filter(location=="China"), aes(x=s_covid, y=s_inc, fill=ncd.deaths))+
  geom_tile()+
  geom_text(aes(label=paste0(signif(prog, digits=2),"%")))+
  scale_fill_gradientn(colors=c("#3c1f5c","#33628e", "#2d7b8d","#20a386", "#fde725"), values=c(0,0.5,1))+
  labs(fill="Total number of NCD deaths (millions)")+
  ylab("Annual absolute increase in coverage (%)")+
  xlab("Covid adjustment factor")+
  ggtitle("Total NCD deaths (millions) and progress towards 40q30 goal (%) \nby each covid and intervention scale-up scenario \n\nChina, 2015-2030")+
labs(caption = "*Text numbers represent the % progress towards achieving 40q30 target")


```


Looking at the covid shock to 40q30 over time

```{r fig.width=8}

base<-all.q30.out%>%filter(s_covid==0 & s_inc==0)%>%mutate(scenario="Baseline")%>%
  select(Adjusted, year_id, location_name, scenario)
best<-all.q30.out%>%filter(s_covid==0 & s_inc==0.05 & year_id>=2019)%>%mutate(scenario="Most optimistic")%>%
  select(Adjusted, year_id, location_name, scenario)
middle<-all.q30.out%>%filter(s_covid==1 & s_inc==0.03 & year_id>=2019)%>%mutate(scenario="Moderate")%>%
  select(Adjusted, year_id, location_name, scenario)
worst<-all.q30.out%>%filter(s_covid==2 & s_inc==0 & year_id>=2019)%>%mutate(scenario="Most pessimistic")%>%
  select(Adjusted, year_id, location_name, scenario)

plot3<-bind_rows(base, best, middle, worst)
plot3$scenario<-factor(plot3$scenario, levels=c("Baseline", "Most pessimistic", "Moderate", "Most optimistic"))

ggplot(plot3%>%filter(location_name=="Brazil"), aes(x=year_id, y=Adjusted, color=scenario))+
  geom_point()+
  ylab("40q30 (%)")+
  xlab("Year")+
  ggtitle("40q30 over time, Brazil")+
  labs(color="Scenario")


## crude average (global)

global<-plot3%>%group_by(scenario,year_id)%>%summarise(q30=mean(Adjusted))

ggplot(global, aes(x=year_id, y=q30, color=scenario))+
  geom_point()+
  ylab("40q30 (%)")+
  xlab("Year")+
  ggtitle("40q30 over time, Global (crude mean)")+
  labs(color="Scenario")

```

Cost  per change in 40q30 vs. cost per DALY averted

```{r fig.width=8}
cost<-read.csv("Outputs/All_ICER_2030.csv", stringsAsFactors = F)%>%select(c(increment, Code, Country, NCD_region, Revised.Intervention.Name))%>%rename(Description = Revised.Intervention.Name)
load("Outputs/icer_rank_output.Rda")

codes<-unique(read_excel("Input_Data/EfficacyData6.xlsx")%>%select(c(Description, NCD)))
codes$NCDcode<-paste0("C", codes$NCD)
codes$NCDcode[codes$Description=="Management of depression disorders with psycological and generic antidepressant therapy"]<-"C2.10"

tot_dalys<-all.dalys%>%rename(Country = location_name)%>%group_by(Country, Code)%>%
  summarise(DALY=sum(DALY.ave))%>%rename(NCDcode = Code)
#just the end change in 2030?
tot_40q30<-all.q30%>%filter(year_id==2030)%>%rename(Country = location_name)%>%
  select(c(Country, Code, q30.ave))%>%rename(NCDcode = Code)

benefits<-full_join(tot_dalys, tot_40q30, by=c("Country", "NCDcode"))
benefits<-left_join(benefits, codes, by="NCDcode")

plot<-na.omit(left_join(cost, benefits, by=c("Description", "Country")))%>%mutate(ICER1 = increment/DALY, ICER2=increment/q30.ave)
plot$platform<-str_extract(plot$Code, "[A-Z]+")

global<-plot%>%group_by(Description, platform)%>%summarise(ICER1=mean(ICER1), ICER2=mean(ICER2))

global$platform<-factor(global$platform, levels=c("HC", "FLH", "RH"), labels=c("Health Centre", "First-level hospital", "Refereal hospital"))

ggplot(global, aes(x=ICER1, y=ICER2, color=platform))+
  geom_point()+
  #geom_text(aes(label=Description), hjust=0, vjust=0)+
  facet_zoom(x = ICER1 >= 0 & ICER1 <= 250)+
  ggtitle("Incremental cost per DALY averted vs. incremental \ncost per change in 40q30 by intervention")+
  labs(color="Platform")+
  xlab("Cost per DALY averted")+
  ylab("Cost per % change in 40q30")


ggplot(global%>%filter(ICER1>1000), aes(x=ICER1, y=ICER2, color=platform))+
  geom_point()+
  geom_text(size=3, aes(label=stringr::str_wrap(Description,70)), position = position_dodge(width=0.9), hjust=0, vjust=1)+
  ggtitle("Incremental cost per DALY averted vs. incremental \ncost per change in 40q30 by intervention")+
  labs(color="Platform")+
  xlab("Cost per DALY averted")+
  ylab("Cost per % change in 40q30")


#this text labeling is horrible.

```
