---
title: "NCDC Costs"
author: "Sarah Pickresgill"
date: "7/16/2021"
output: html_document
---
# Install the package
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls()) #Remove all
library(dplyr)
library(ggplot2)
library(readxl)
library(tidyverse)
library(kableExtra)
library(reshape2)
library(stringr)

'%!in%' <- function(x,y)!('%in%'(x,y))
```

# Functions
```{r}
tradable_conversion <- function(unit_cost, tradable_ratio, currency, global_inflation, exchange){
  if(currency == "USD") {
    unit_cost*tradable_ratio*global_inflation} else {
      ((unit_cost*tradable_ratio)/exchange)*global_inflation
    }
}

nontradable_conversion <- function(unit_cost,tradable_ratio, currency, cpi_adjust, exchange,country, exchange_end, gni, gni_selected_country){
  if(currency == "USD" & (country == "LIC" | country == "LMIC" | country == "LIC+LMIC+UMIC")) {
    unit_cost*(1-tradable_ratio)*cpi_adjust*(gni_selected_country/gni)
  } else if (currency == "USD" & (country != "LIC" & country != "LMIC" & country != "LIC+LMIC+UMIC")){
    ((unit_cost*exchange)*(1-tradable_ratio))*cpi_adjust/exchange_end*(gni_selected_country/gni)} 
  else {
      ((unit_cost*(1-tradable_ratio)*cpi_adjust)/exchange_end)*(gni_selected_country/gni)
    }
}
```

# Install the necessary input files
```{r}
load("output/Optim.Out0830.Rda")
#intersectoral only
#regions<-read.csv("../new_inputs/Country_groupings.csv")%>%
#    select(c(Country, NCD_region))%>%rename(location_name=Country)
#deaths_avert<-left_join(dadt.all.opt, regions, by="location_name")%>%filter(byear==2015)%>%
#  group_by(NCD_region)%>%summarise(DA=sum(Deaths.Avert))

all.pin.opt<-all.pin.opt%>%filter(byear==2015)
all.pin.opt$unique_id<-paste0("C", all.pin.opt$Code, "_", all.pin.opt$sub_id)
dadt.all.opt<-dadt.all.opt%>%filter(byear==2015)
dalys.opt<-dalys.opt%>%filter(byear==2015)
q30.CodeDelta<-q30.CodeDelta%>%filter(byear==2015)

# Unit cost adjustment
uc <- read.csv("../new_inputs/PINandCosts0625.csv", stringsAsFactors=F)
uc$unique_id <- paste0("C",uc$NCD,"_",uc$sub_id)

#table(uc$unique_id)
uc <- uc %>%filter(Original.Currency != "NA")

# Necessary files
# Exchange rate
exchange <- read_xlsx("../new_inputs/Exchange_rate.xlsx", na = "..")
exchange<-exchange[,c(1:60)]
ex2<-read_xlsx("../new_inputs/Exchange_rate_2020.xlsx", skip=3)
ex2<-ex2[,c(1,61,62)]

exchange<-left_join(exchange, ex2, by="Country")
exchange <- exchange%>%gather(year, value, -Country)%>%group_by(Country)%>%fill(value)%>%spread(year, value)


# Regional inflation
#regional_inflation <- read_xls("../new_inputs/Regional_inflation_20200212.xls", sheet = "Data")
regional_inflation <- read_xls("../new_inputs/Regional_inflation_2020.xls", sheet = "Data", skip=3)
#regional_inflation[,c(5:64)] <- (regional_inflation[,c(5:64)]/100)+1
regional_inflation[,c(5:65)] <- (regional_inflation[,c(5:65)]/100)+1

# COUntry grouping
class <- read.csv("../new_inputs/Country_groupings.csv")

#Country list: only eligible countries
table(class$NCD_region)
country_list <- class %>% 
  filter(World_bank == "LIC" | World_bank == "LMIC"| World_bank == "UMIC") %>% 
  filter(NCD_region %in% c("Latin America and Caribbean",
         "Central and Eastern Europe",
         "Central Asia, Middle East and North Africa",
         "Sub-Saharan Africa",
         "South Asia",
         "East and South East Asia",
         "Oceania")) %>% 
  select(World_bank, NCD_region ,Country, iso3)


# CPI adjusted
cpi <- read.csv("../new_inputs/CPI_WB_2018_added2.csv", stringsAsFactors=F)
cpi<-cpi[,-c(66:71)]
#add 2020 data
cpi2<-read.csv("../new_inputs/CPI_2020.csv", stringsAsFactors=F)
names(cpi2)[1]<-"Country"
cpi2<-cpi2[,c(1,65)]
cpi<-left_join(cpi, cpi2, by="Country")

cpi <- cpi[,c(3,6:66)]%>%gather(year, value, -Country)%>%group_by(Country)%>%fill(value)%>%spread(year, value)

#also add France
#france<-read.csv("../new_inputs/CPI_2020.csv", stringsAsFactors=F)%>%filter(Country.Code=="FRA")
#names(france)[1]<-"Country"
#cpi<-bind_rows(cpi, france[,-c(2,3,4)])

# GNI
GNI <- read.csv("../new_inputs/GNI_WB_USD_2017_re2.csv", stringsAsFactors=F)
GNI<-GNI[,-c(1,4,5,6,66,67,68)]
GNI2 <- read.csv("../new_inputs/GNI_2020.csv", stringsAsFactors=F)
GNI2<-GNI2[,c(1,64,65)]
names(GNI2)[1]<-"Country"

GNI<-left_join(GNI, GNI2, by="Country")
GNI <- GNI%>%gather(year, value, -Country, -Country.Code)%>%group_by(Country.Code)%>%fill(value)%>%spread(year, value)
#load("../new_demography/output/icer_rank_output.Rda")

```


# Table2 (NCD interventions): Based on ICER ranking
```{r data install}

#country list of no alcohol
noalc.list<-c("Afghanistan", "Bangladesh", "Iran", "Libya", "Sudan", "Yemen")

#list of alcohol policy unique_ids
intersectoral.alc<-c("5.2_a", "5.4_a")

###########################################  
##update PIN for intersectoral policies##
############################################

#convert intersectoral PIN back to total pop for years 2023-2030
all.pin.opt$pin[all.pin.opt$group=="Adjsuted" & all.pin.opt$Code>5 & all.pin.opt$year_id>=2023]<- all.pin.opt$pin[all.pin.opt$group=="Adjsuted" & all.pin.opt$Code>5& all.pin.opt$year_id>=2023]/all.pin.opt$Coverage[all.pin.opt$group=="Adjsuted" & all.pin.opt$Code>5& all.pin.opt$year_id>=2023]

#scale-up coverage (1/3 in 2023, 2/3 in 2024, full coverage 2025-2030)
all.pin.opt$pin[all.pin.opt$group=="Adjsuted" & all.pin.opt$Code>5 & all.pin.opt$year_id==2023]<- (1-(all.pin.opt$Coverage[all.pin.opt$group=="Adjusted" & all.pin.opt$Code>5 & all.pin.opt$year_id==2023]-0.1))*(1/3)


##edit for countries in which alcohol is banned##
all.pin.opt$pin[all.pin.opt$unique_id%in%intersectoral.alc & all.pin.opt$location_name%in%noalc.list]<-0


benefits.opt <- merge(y = dalys.opt, x = class, by.x = "Country", by.y = "location_name")
```

# Settings
```{r}
#Setting
#tradable_ratio <- 0.3
UC_Years <- 2020  # The output year
# ancillary_HF_cost <- 0.5 # possible change
# above_HF <- 0.17 # possible change
```

```{r data.frame development}
final_all <- data.frame(Code = character() ,
                        adjusted_uc = numeric(),
                        pin_sum= numeric(),
                        year_id =  numeric(),
                        total_cost = numeric(),
                        senario = character() ,
                        Country = character(),
                        Class = character(),
                        Region = character(),
                        stringsAsFactors=FALSE)


final_all_intervention <- data.frame(Code = character(),
                                     Intervention = character(),
                                     senario = character() ,
                                     Country = character(),
                                     adjusted_uc = numeric(),
                                     pin_sum = numeric(),
                                     total_cost = numeric(),
                                     Region = character(),
                                     stringsAsFactors=FALSE) 




final_all_ICER <- data.frame(Country = character(),
                             year_id = numeric(),
                             Region = character(),
                             sum_increment = numeric(),
                             life_years_gained = numeric(),
                             ICER = numeric()
)

increment_all_year      <- data.frame(
                             unique_id = character(),
                             year_id = numeric(),
                             Class = character(),
                             Region = character(),
                             adjusted_uc = numeric(),
                             base_pin = numeric(),
                             base_total = numeric(),
                             adjust_pin = numeric(),
                             adjust_total = numeric(),
                             increment = numeric()
)
```


```{r re-run}
# Calculate adjusted costs & total by interventions
i <- 1
c <- 1
n <- 1
y <- 1

for (c in c(1:85, 87:124)){
 
  selected_country <- as.character(country_list$Country[c])
  selected_country_code <- as.character(country_list$iso3[c])
  selected_country_category <- as.character(country_list$World_bank[c])
  selected_country_region <- as.character(country_list$NCD_region[c])
  
  country_class <- as.character(country_list[country_list$Country == selected_country,]$World_bank) 
# Adjusted UC install
# Adjustment database
  no <- nrow(uc)

  file.name <- paste0("../new_demography/output/costs/bycountry/",selected_country,"_adjusted_uc_",UC_Years,".csv")
  adjusted_uc <- read.csv(file.name)
        
# Adjusted UC end 
     
    result.df <- adjusted_uc %>% select(unique_id)
    result.df2 <- adjusted_uc %>% select(unique_id)

    
# full data -----------------------
  country.pop <- all.pin.opt %>% 
  filter(location_name == selected_country)
    
  full.data <- merge.data.frame(x = country.pop, y = adjusted_uc[,c("unique_id", "Original.Unit.Cost", "Cost.adjustment", "Traded", "tradable_uc", "nontradable_uc", "adjusted_uc" )], by = "unique_id", all.x = T)

  full.data$total_cost <- full.data$pin * full.data$adjusted_uc
  
  #file.name <- paste0("Result_0706/Optimal/All_pop_cost/",selected_country,"_all_by_intervention_year",".csv")
  #write.csv(full.data, file.name)
  
    
# Baseline population in need------------------
for (y in 3:10){
  
##PIN by intervention
# pin_group = all code
pin_group <- all.pin.opt %>% 
  filter(location_name == selected_country,
         year_id == 2020 + y, 
         group == "Baseline") %>% 
  group_by(unique_id) %>% 
  summarize(pin_sum = sum(pin))

pin_group$year_id <- 2020 + y

uc_pin <- merge.data.frame(adjusted_uc, pin_group, by = "unique_id")

uc_pin <- uc_pin %>% 
  mutate(total_cost = adjusted_uc * pin_sum)

uc_pin_all <- if(y == 3) {
  uc_pin
} else {
  rbind(uc_pin_all, uc_pin)
}

result.df <- merge(result.df, uc_pin[,c("unique_id","total_cost")], by = "unique_id")

label <- paste0("cost_",2020+y)
names(result.df)[ which( names(result.df)=="total_cost" ) ] <- label
}

  
# By Interventions
final.df1_int <- result.df
final.df1_int$senario <- "Baseline"
final.df1_int$Country <- selected_country
final.df1_int$Class <- country_class
final.df1_int$Region <- selected_country_region

final.df1_int$total_cost <- apply(final.df1_int[,2:9],1,sum)

# Add unit cost
final.df1_int <- merge(final.df1_int, uc_pin[,c("unique_id", "adjusted_uc")] , by = "unique_id")

# Add pin
pin_code <- all.pin.opt %>% 
  filter(location_name == selected_country,
         group == "Baseline") %>% 
  group_by(unique_id) %>% 
  summarize(pin_sum = sum(pin))

final.df1_int <- merge(final.df1_int, pin_code[,c("unique_id", "pin_sum")], by = "unique_id")

 # final.df1_int <- final.df1_int %>%
 #   select(unique_id, senario, Country, adjusted_uc, pin_sum ,total_cost, Region)
 # 

# years
result.df1_long <- uc_pin_all

result.df1_long$senario <- "Baseline"
result.df1_long$Country <- selected_country
result.df1_long$Class <- country_class
result.df1_long$Region <- selected_country_region





#Adjustment-------------

for (y in 3:10){
#PIN by intervention

# pin_group = all code
pin_group <- all.pin.opt %>% 
  filter(location_name == selected_country,
         year_id == 2020 + y, 
         group == "Adjusted") %>% 
  group_by(unique_id) %>% 
  summarize(pin_sum = sum(pin))

pin_group$year_id <- 2020 + y

uc_pin <- merge.data.frame(adjusted_uc, pin_group, by = "unique_id")

uc_pin <- uc_pin %>% 
  mutate(total_cost = adjusted_uc * pin_sum)

uc_pin_all <- if(y == 3) {
  uc_pin
} else {
  rbind(uc_pin_all, uc_pin)
}

result.df2 <- merge(result.df2, uc_pin[,c("unique_id","total_cost")], by = "unique_id")

label <- paste0("cost_",2020+y)
names(result.df2)[ which( names(result.df2)=="total_cost" ) ] <- label

}

# By intervention & save

final.df2_int <- result.df2
final.df2_int$senario <- "Adjusted"
final.df2_int$Country <- selected_country
final.df2_int$Class <- country_class
final.df2_int$Region <- selected_country_region

final.df2_int$total_cost <- apply(final.df2_int[,2:9],1,sum)

# Add unit cost
final.df2_int <- merge(final.df2_int, uc_pin[,c("unique_id", "adjusted_uc")])

# Add pin
pin_code <- all.pin.opt %>% 
  filter(location_name == selected_country, 
         group == "Adjusted") %>% 
  group_by(unique_id) %>% 
  summarize(pin_sum = sum(pin))

final.df2_int <- merge(final.df2_int, pin_code[,c("unique_id", "pin_sum")])

# 
#  final.df2_int <- final.df2_int %>% 
#    select(Code, senario, Country, adjusted_uc, pin_sum ,total_cost, Region)
  
final_country_tc_int <- rbind(final.df1_int,final.df2_int)


#Final dataset by interventions-------------------
file.name <- paste0("Result_0706/Optimal/Total_cost_intervention/",selected_country,"_total_cost_2030_intervention",".csv")
#write.csv(final_country_tc_int, file.name)

final_all_intervention <- rbind(final_all_intervention, final_country_tc_int)
#--------------------------------------------------

# By year
result.df2_long <- uc_pin_all

result.df2_long$senario <- "Adjusted"
result.df2_long$Country <- selected_country
result.df2_long$Class <- country_class
result.df2_long$Region <- selected_country_region

# Save
final_country_tc3 <- rbind(result.df1_long,result.df2_long)
file.name <- paste0("Result_0706/Optimal/Total_cost_year/",selected_country,"_total_cost_2030",".csv")
#write.csv(final_country_tc3, file.name)

#Final dataset-------------------
  final_all <- rbind(final_all, final_country_tc3)

# ----------------------
# incremental cost by year and intervention
base_result <- result.df1_long %>% 
  filter(senario == "Baseline")%>% 
  select(unique_id, Country, Class, Region, year_id, adjusted_uc, pin_sum, total_cost) %>% 
  rename(base_pin = pin_sum,
         base_total = total_cost) 

adjust_result <- result.df2_long %>%
  filter(senario == "Adjusted") %>% 
  select(unique_id, year_id, pin_sum, total_cost) %>% 
  rename(adjust_pin = pin_sum,
         adjust_total = total_cost) 


increment_by_year <- merge(base_result, adjust_result , by = c("unique_id", "year_id"))

increment_by_year$incremental <- increment_by_year$adjust_total - increment_by_year$base_total

file.name <- paste0("Result_0706/Optimal/incremental_cost_year/",selected_country,"_increment_cost_2020_2030",".csv")
#write.csv(increment_by_year, file.name)

increment_all_year <- rbind(increment_all_year, increment_by_year)

country.all.id <- colsplit(increment_by_year$unique_id,"_",names=c("Code","sub_id"))
# From unique_id to Code
increment_by_year$Code <- country.all.id$Code
increment_by_year$sub_id <- country.all.id$sub_id


country.all.sum <- increment_by_year %>% 
  group_by(Country, Region, year_id) %>% 
  summarize(sum_increment = sum(incremental))


# Benefit
benefits.country <- benefits.opt %>% 
  filter(Country == selected_country) 


country.all2 <- merge(x = country.all.sum, y = benefits.country[,c("Country", "year_id", "DALY.ave")], by = c("Country", "year_id"),all.x = T)


country.all2 <- country.all2 %>% 
  mutate(ICER = sum_increment / DALY.ave
         )

file.name <- paste0("output/",selected_country,"_ICER_2020_2030",".csv")
#write.csv(country.all2, file.name)

final_all_ICER <- rbind(final_all_ICER, country.all2)

}

```

```{r}
file.name <- paste0("output/Optimal/All_TC_2030_0830",".csv")
write.csv(final_all, file.name)

file.name <- paste0("output/Optimal/All_Intervention_2030_0830",".csv")
write.csv(final_all_intervention, file.name)

file.name <- paste0("output/Optimal/All_ICER_2030_0830",".csv")
write.csv(final_all_ICER, file.name)
```


```{r Table 3 generate}
#all<- final_all_intervention
load("output/Optim.Out0830.Rda")
file.name <- paste0("output/Optimal/All_Intervention_2030_0830",".csv")
all <- read.csv(file.name)

## add intersectoral costs##
int_cost<-read.csv("output/costs/All_total_cost_2030_intervention_0830.csv", stringsAsFactors = F)%>%select(-c(X))%>%
  mutate(unique_id = paste0("C",unique_id))%>%filter(substr(unique_id,1,2)=="C5")

all<-bind_rows(all, int_cost)
##

all_int_base <- all %>% 
  filter(senario == "Baseline") %>% 
  group_by(Region) %>% 
  filter(is.na(total_cost) == F) %>% 
  summarize(total_cost_base = sum(total_cost))

all_int_ad <- all %>% 
  filter(senario == "Adjusted") %>% 
  group_by(Region) %>% 
  filter(is.na(total_cost) == F) %>% 
  summarize(total_cost_adjust = sum(total_cost))

all_int_dif <- merge(all_int_base, all_int_ad, by = c("Region"), all.x = T )

all_int_dif$increment <- all_int_dif$total_cost_adjust - all_int_dif$total_cost_base

sum_total_base <- sum(all_int_dif$total_cost_base)
sum_total_ad <- sum(all_int_dif$total_cost_adjust)
sum_total_increment <- sum(all_int_dif$increment)

all_int_dif$Region <- as.character(all_int_dif$Region)

All <- c("All", sum_total_base, sum_total_ad, sum_total_increment)

table3 <- rbind(all_int_dif,All)
#Numeric
table3$total_cost_base <- as.numeric(table3$total_cost_base)
table3$total_cost_adjust <- as.numeric(table3$total_cost_adjust)
table3$increment <- as.numeric(table3$increment)

table3[,2:4] <- round(table3[,2:4] / 1000000000,2)


table3 <- table3[c(4,1,2,7,6,3,5,8),]

table3[,2:4] <- round(table3[,2:4] / 8,2) #annual

#add per capita column 4
#load("../new_inputs/PreppedData.Rda")
#pop<-wpp.in%>%filter(year==2019)%>%group_by(location_name)%>%
#  summarise(pop=sum(Nx))%>%rename(Country=location_name)

regions<-read.csv("../new_inputs/Country_groupings.csv")%>%
    select(c(Country, NCD_region))

#pop<-na.omit(left_join(pop, regions, by="Country")%>%group_by(NCD_region)%>%
#               summarise(Nx=sum(pop))%>%rename(Region=NCD_region))

#write.csv(pop, "../new_inputs/wpp_pop_region.csv", row.names = F)
pop<-read.csv("../new_inputs/wpp_pop_region.csv", stringsAsFactors = F)

table3<-left_join(table3,pop,by="Region")
allpop<-sum(table3$Nx, na.rm=T)
table3$Nx[table3$Region=="All"]<-allpop

table3$increment_pc<-1e9*table3$increment/table3$Nx

#add net economic benefit per capita column 5
dth_avert<-left_join(dadt.all.opt, regions%>%rename(location_name=Country), by="location_name")%>%group_by(NCD_region)%>%filter(byear==2015)%>%summarise(DA = sum(Deaths.Avert))

dth_avert<-bind_rows(dth_avert, data.frame(NCD_region="All", DA=sum(dth_avert$DA)))%>%rename(Region = NCD_region)

#diffq30<-left_join()

gdp <- read.csv("../new_inputs/GDP_per_2017_NCD_region_0608.csv")
vsl<-left_join(gdp%>%rename(Region = NCD_region), pop, by="Region")

all.gdp<-vsl%>%summarise(GDP_2017=sum(GDP_2017), pop_2017_sum=sum(pop_2017_sum),
                         GNI=sum(GNI), Nx=sum(Nx))
all.gdp<-all.gdp%>%mutate(GNIpc=GNI/pop_2017_sum, GDP_2017_capita=GDP_2017/pop_2017_sum, Region="All")

vsl<-bind_rows(vsl%>%select(-c(X)), all.gdp)

us.vsl<-9400000
us.gni.pc<-57900
elasticity<-1.1

#vsl$VSL2<-((vsl$GNIpc/us.gni.pc)^elasticity)*us.vsl
vsl<-left_join(vsl, dth_avert, by="Region")

vsl<-left_join(vsl, table3%>%select(c("Region", "increment")), by="Region")
vsl$increment<-vsl$increment*8

#vsl$econ<-vsl$DA*vsl$VSL2
#vsl$net<-vsl$econ-vsl$increment*1e9
#vsl$netpc<-vsl$net/vsl$pop_2017_sum
#vsl$BCR<-vsl$econ/(vsl$increment*1e9)

vsl$VSL<-(20*us.gni.pc)*(vsl$GNIpc/us.gni.pc)^elasticity
vsl$econ.bns<-(vsl$VSL*vsl$DA)/1e9
vsl$net.econ.pc<-(((vsl$econ.bns-vsl$increment)*1e9)/vsl$pop_2017_sum)
vsl$net.econ.total<-(((vsl$econ.bns-vsl$increment)*1e9))

table3<-left_join(table3%>%select(-c(Nx)), vsl%>%select(c(Region, DA, net.econ.pc, net.econ.total)), by="Region")
table3$DA<-table3$DA/1000
#table3[,5:7]<-round(table3[,5:7])

#add benefit cost ratio
table3$benefit.cost.ratio<-round(table3$net.econ.pc/(table3$increment_pc*8),2)

table3$total_cost_adjust_8year<-table3$total_cost_adjust*8
table3$total_cost_base_8year<-table3$total_cost_base*8
table3$increment_8year<-table3$increment*8
table3$cost.per.DA<-(1e9*table3$increment_8year)/(table3$DA*1000)

write.csv(table3, "Figures/Table3_0830.csv")

vsl<-vsl%>%select(c(Region, increment, DA, VSL, econ.bns, net.econ.pc))
vsl$DA<-vsl$DA/1000
vsl$VSL<-vsl$VSL/1000

vsl$benefit.cost.ratio<-vsl$econ.bns/vsl$increment
vsl<-vsl[c(4,1,2,7,6,3,5,8),]

write.csv(vsl, "Figures/Appendix-tableA6_0830.csv")
```

## Table 2 from Will

```{r}

pacman::p_load(data.table, dplyr, tidyr, progress, pspline, MortalityLaws) 
# Appendix Table

load("output/Optim.Out0830.Rda")
regs = c("Latin America and Caribbean","Central and Eastern Europe",
         "Central Asia, Middle East and North Africa","Sub-Saharan Africa",
         "South Asia","East and South East Asia","Oceania","All low- and middle-income countries")

count_g <- fread("../new_inputs/Country_groupings.csv") %>%
  right_join(country.lab, by = "iso3")

q30.reaches <- q30.CodeDelta %>% 
  left_join(count_g %>% select(location_name, NCD_region), by = "location_name")

q30.reaches <- q30.reaches %>% mutate(NCD_region = "All low- and middle-income countries") %>%
  rbind(q30.reaches) %>% mutate(NCD_region = factor(NCD_region, levels = regs)) %>%
  arrange(NCD_region)

q30.summary1 <- q30.reaches %>% mutate(CodeDelta = as.numeric(n.inters)) %>%  
  group_by(NCD_region, byear) %>% 
  summarise(MinInts = min(CodeDelta), MedInt = median(CodeDelta), .groups = "drop") %>% 
  ungroup()

q30.summary1 <- q30.reaches %>% 
  mutate(Count = 1) %>%
  group_by(NCD_region, Reaches, byear) %>% summarise(Count = sum(Count), .groups = "drop") %>% ungroup() %>% 
  spread(Reaches, Count) %>% 
  mutate(no = ifelse(is.na(no), 0, no), yes = ifelse(is.na(yes), 0, yes)) %>% 
  right_join(q30.summary1, by = c("NCD_region","byear")) %>% 
  arrange(NCD_region, byear) 

da <- dadt.all.opt %>% mutate(Deaths.Avert = ifelse(Deaths.Avert < 0, 0, Deaths.Avert)) %>%
  left_join(count_g %>% select(Country, NCD_region) %>% rename(location_name = Country), by = "location_name") %>% 
  group_by(age_group, NCD_region, byear) %>% summarise(Deaths.Avert = sum(Deaths.Avert), .groups = "drop") %>% ungroup()

da <- da %>% mutate(NCD_region = "All low- and middle-income countries") %>%
  group_by(age_group, NCD_region, byear) %>% summarise(Deaths.Avert = sum(Deaths.Avert), .groups = "drop") %>% ungroup() %>%
  rbind(da) %>% mutate(NCD_region = factor(NCD_region, levels = regs)) %>% arrange(NCD_region) %>% 
  mutate(Deaths.Avert = 10*round(ceiling(Deaths.Avert/10000))) %>%
  spread(age_group, Deaths.Avert)

save(q30.summary1, da, file = "output/Optim.Out.Tables0830.Rda")

inters<-q30.reaches%>%filter(byear==2015)%>%
  rename(reached = n.inters)%>%select(c(reached, location_name, NCD_region))

table2<-left_join(q30.code, inters, by="location_name")%>%group_by(location_name)%>%filter(n.inters == reached)
table2$base_diff<-100*(table2$`40q30_15`-table2$`40q30_2030_base`)/table2$`40q30_15`
table2$adj_diff<-100*(table2$`40q30_15`-table2$`40q30_2030_adj`)/table2$`40q30_15`
table2$added.reduction<-table2$adj_diff-table2$base_diff
table2$base.reach<-0
table2$base.reach[table2$`40q30_2030_base`<=table2$Target_15]<-1

table2$adj.reach<-0
table2$adj.reach[table2$`40q30_2030_adj`<=table2$Target_15]<-1

table2$reach80<-0
table2$reach80[table2$adj_diff>=80*(1/3)]<-1

print_table2<-table2%>%group_by(NCD_region)%>%summarise(base.diff.med = median(base_diff), 
                                                  base.diff.iqr25=quantile(base_diff, 0.25),
                                                  base.diff.iqr75=quantile(base_diff, 0.75),
                                                  base.reach.prop = 100*sum(base.reach)/n(), 
                                                  med.int = median(n.inters), 
                                                  adj.diff.med=median(adj_diff), 
                                                  adj.diff.iqr25=quantile(adj_diff, 0.25),
                                                  adj.diff.iqr75=quantile(adj_diff, 0.75),
                                                  adj.reach.prop = 100*sum(adj.reach)/n(), 
                                                  reach.80.prop = 100*sum(reach80)/n()
                                                  )


write.csv(print_table2, "Figures/Table2_0830.csv")
```


# Data for Adrian
```{r}
file.name <- paste0("output/Optimal/All_Intervention_2030_0830",".csv")
all <- read.csv(file.name)

##add intersectoral costs##
int_cost<-read.csv("output/costs/All_total_cost_2030_intervention_0830.csv", stringsAsFactors = F)%>%select(-c(X))%>%
  mutate(unique_id = paste0("C",unique_id))%>%filter(substr(unique_id,1,2)=="C5")

all<-bind_rows(all, int_cost)

sum_country <- all %>% 
  group_by(Country, Region, Class, senario) %>% 
  summarize(
            total_cost_2023 = sum(cost_2023),
            total_cost_2024 = sum(cost_2024),
            total_cost_2025 = sum(cost_2025),
            total_cost_2026 = sum(cost_2026),
            total_cost_2027 = sum(cost_2027),
            total_cost_2028 = sum(cost_2028),
            total_cost_2029 = sum(cost_2029),
            total_cost_2030 = sum(cost_2030),
            total_cost_all = sum(total_cost))

sum_country2 <- merge(country_list, sum_country, by = "Country")

write.csv(sum_country2, "Figures/Total_cost_NCD_forAdrian0830.csv")
```

# Appendix Table A4
```{r additional table}

rank<-read.csv("output/All_ICER_2030_0830.csv", stringsAsFactors = F)
rank$included<-NA
  
load("output/Optim.Out0830.Rda")

for(i in unique(q30.CodeDelta$location_name)){
  
  max<-q30.CodeDelta$n.inters[q30.CodeDelta$location_name==i & q30.CodeDelta$byear==2015]

  rank$included[rank$Country==i & rank$ICER_rank2<=max]<-1
  rank$included[rank$Country==i & rank$ICER_rank2>max]<-0
  
}

tableA3<-rank%>%group_by(Code)%>%summarise(Median.rank=median((ICER_rank2)), Prop.included=sum(included)/123)
  
names <- read.csv("../new_inputs/names.csv", header=TRUE, stringsAsFactors=FALSE)
names$Code<-as.numeric(gsub("C", "", names$Code))

tableA3<-left_join(tableA3, names, by="Code")
tableA3<-tableA3[order(tableA3$Median.rank, decreasing = FALSE),]

write.csv(tableA3, "../new_demography/Figures/Appendix-tableA4_0830.csv")

```

#Appendix Table A5

```{r}
regions<-read.csv("../new_inputs/Country_groupings.csv")%>%
    select(c(Country, NCD_region))%>%rename(location_name=Country)

ta6<-left_join(dadt.all.opt%>%filter(byear==2015), regions, by="location_name")

ta6<-ta6%>%group_by(age_group, NCD_region)%>%summarise(Deaths.averted.thousands = round(sum(Deaths.Avert)/1000))

ta6<-ta6%>%spread(age_group, Deaths.averted.thousands)

ta<-ta6[,c(1,4,2,3)]

write.csv(ta, "../new_demography/Figures/Appendix-tableA5_0830.csv")

```

#Appendix Table A9
```{r}
tc<-read.csv("../new_demography/output/Optimal/All_Intervention_2030_0830.csv")
ta9<-tc%>%group_by(Region, senario)%>%summarise(tc=sum(total_cost)/1e9)%>%spread(senario, tc)

ta9<-ta9[,c(1,3,2)]
ta9$Increment<-ta9$Adjusted-ta9$Baseline

#write.csv(ta9, "../new_demography/Figures/TableA9.csv")

```


